import 'package:curitalk/app/theme/tokens/tokens.dart';
import 'package:flutter/material.dart';

abstract final class AppColorScheme {
  static const ColorScheme light = ColorScheme.light(
    primary: AppPalette.primary,
    onPrimary: AppPalette.onPrimary,
    primaryContainer: AppPalette.primary,
    onPrimaryContainer: AppPalette.onPrimary,
    primaryFixed: AppPalette.blockLilacSoft,
    primaryFixedDim: AppPalette.blockLilac,
    onPrimaryFixed: AppPalette.ink,
    onPrimaryFixedVariant: AppPalette.inkSecondary,
    secondary: AppPalette.inkSecondary,
    onSecondary: AppPalette.onPrimary,
    secondaryContainer: AppPalette.surfaceSoft,
    onSecondaryContainer: AppPalette.ink,
    secondaryFixed: AppPalette.surfaceSoft,
    secondaryFixedDim: AppPalette.hairline,
    onSecondaryFixed: AppPalette.ink,
    onSecondaryFixedVariant: AppPalette.inkSecondary,
    tertiary: AppPalette.accentTerracotta,
    onTertiary: AppPalette.onPrimary,
    tertiaryContainer: AppPalette.blockCoral,
    onTertiaryContainer: AppPalette.ink,
    tertiaryFixed: AppPalette.blockCoral,
    tertiaryFixedDim: AppPalette.accentTerracotta,
    onTertiaryFixed: AppPalette.ink,
    onTertiaryFixedVariant: AppPalette.accentTerracotta,
    error: AppPalette.semanticError,
    onError: AppPalette.onPrimary,
    errorContainer: AppPalette.errorContainer,
    onErrorContainer: AppPalette.semanticError,
    surface: AppPalette.canvas,
    onSurface: AppPalette.ink,
    surfaceDim: AppPalette.hairlineSoft,
    surfaceBright: AppPalette.canvas,
    surfaceContainerLowest: AppPalette.canvas,
    surfaceContainerLow: AppPalette.surfaceSubtle,
    surfaceContainer: AppPalette.surfaceSoft,
    surfaceContainerHigh: AppPalette.hairlineSoft,
    surfaceContainerHighest: AppPalette.hairline,
    onSurfaceVariant: AppPalette.inkSecondary,
    outline: AppPalette.hairline,
    outlineVariant: AppPalette.hairlineSoft,
    shadow: AppPalette.overlayScrim,
    scrim: AppPalette.overlayScrim,
    inverseSurface: AppPalette.blockNavy,
    onInverseSurface: AppPalette.inverseInk,
    inversePrimary: AppPalette.blockLilacSoft,
    surfaceTint: AppPalette.canvas,
  );
}
